require("test/spec/arrayToObject");
require("test/spec/extend");
require("test/spec/merge");
require("test/spec/identity");
require("test/spec/noop");
require("test/spec/objectValue");
require("test/spec/pick");
require("test/spec/omit");
require("test/spec/isMatch");
